language: go

go:
  - 1.13

before_install:
  - go get -t -v ./ably/...
env:
  - GOMAXPROCS=4 GO111MODULE=on
sudo: false
script:
  - make build
  - if ! (git status | grep "working tree clean"); then echo "uncommitted generated code; run 'make build' and commit the result"; exit 1; fi
  - make test
